version: '3.3'
services:
  app:
    image: node:12-buster-slim
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "npm install && npm run dev"
    ports:
      - 3030:8080
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    restart: always

